[project]
name = "myoconverter"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Your Name", email = "you@example.com" }
]
requires-python = ">=3.11,<3.12"

dependencies = [
    "loguru>=0.7.0,<0.8.0",
    "lxml>=4.9.2,<5.0.0",
    "numpy==1.26.4",
    "scipy>=1.11.1,<2.0.0",
    "scikit-learn>=1.3.0,<2.0.0",
    "matplotlib>=3.7.1,<4.0.0",
    "trimesh>=3.22.3,<4.0.0",
    "pyvista>=0.40.0,<1.0.0",
    "networkx>=3.1,<4.0",
    "fpdf2>=2.7.4,<3.0.0",
    "seaborn>=0.12.2,<1.0.0",
    "mujoco>=2.3.6,<3.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.9",
    "ty>=0.0.29",
]


[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
ignore = ["COM812"]
preview = true
extend-select = [
  "ASYNC", # flake8-async
  "S",     # flake8-bandit
  "YTT",   # flake8-2020
  "ANN",   # flake8-annotations
  "BLE",   # flake8-blind-except
  "FBT",   # flake8-boolean-trap
  "B",     # flake8-bugbear
  "A",     # flake8-builtins
  "COM",   # flake8-commas
  "C4",    # Catch incorrect use of comprehensions, dict, list, etc
  "DTZ",   # flake8-datetimez
  "T10",   # flake8-debugger
  "EM",    # flake8-errmsg
  "EXE",   # flake8-executable
  "FIX",   # flake8-fixme
  "FA",    # flake8-future-annotations
  "INT",   # flake8-gettext
  "ISC",   # Good use of string concatenation
  "ICN",   # Use common import conventions
  "LOG",   # flake8-logging
  "G",     # flake8-logging-format
  "INP",   # flake8-no-pep420
  "PIE",   # flake8-pie
  "T20",   # flake8-print
  "PYI",   # flake8-pyi
  "PT",    # flake8-pytest-style
  "Q",     # flake8-quotes
  "RSE",   # flake8-raise
  "RET",   # Good return practices\
  "SLF",   # flake8-self
  "SIM",   # Common simplification rules
  "SLOT",  # flake8-slots
  "TID",   # Some good import practices
  "TD",    # Be diligent with TODO comments
  "TC",    # Enforce importing certain types in a TYPE_CHECKING block
  "ARG",   # flake8-unused-arguments
  "PTH",   # Use pathlib instead of os.path
  "FLY",   # flynt
  "I",     # Sort imports properly
  "C90",   # mccabe
  "NPY",   # Some numpy-specific things]
  "PD",    # pandas-vet
  "N",     # pep8-naming
  "PERF",  # perflint
  "E",     # PyCodeStyle errors
  "W",     # PyCodeStyle warnings
  "F",     # Pyflakes rules
  "PL",    # pylint
  "UP",    # Warn if certain things can changed due to newer Python versions
  "FURB",  # refurb
  "RUF",   # ruff-specific rules
  "TRY",   # tryceratops
]
[tool.ruff.format]
preview = true
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ty.rules]
all = "error"

